### ISSUE TITLE
THESIS

### ISSUE THREAD

**Issue by tcpipchip** [royyandzakiy/LoRa-RHMesh#1]
Hi @royyandzakiy 

I want to test your MESH on my 3 LOM204
i am using the RF_95
Can you send me your doc thesis to read it?

I want to understand how you figure out the MESH NODES and and if there is some MESH SERVER...

Thanks

**Comment by royyandzakiy** [comment]
Hi, sure. Should I send it here?

**Comment by tcpipchip** [comment]
Yes, or to tcpipchip@hotmail.com too

**Comment by tcpipchip** [comment]
tks

**Comment by tcpipchip** [comment]
examples running! but i need to understand the Theory :)

**Comment by royyandzakiy** [comment]
Here you go, but it is in Indonesian. Feel free to ask anything about it.

Cheers,
  2-20 - Laporan-IF4092-TA2-2019-Royyan Abdullah Dzakiy.pdf
<https://drive.google.com/file/d/131HOW_rC66NNzijl9VL7-61Q9-HlTkup/view?usp=drivesdk>

**Comment by tcpipchip** [comment]
Hi
No problem! I translate it! 
i have 3 modules to test lora!  
my questions are:
-one must to be a server/bridge?
-other 2 must to be nodes ?
-each node must have have your ID (1,2,..) ?
-the only that can transmit data must to be the nodes ? And all will transmite to server/bridge ?
-or are data transmission bidirecional ? 
-on GitHub, wich 3 examples must i burn on my 3 modules ?

thanks!!!

**Comment by royyandzakiy** [comment]
I might need to actually test it myslef, it has been 3 years since I last
touched that code haha. What about we arrange an online meet, and I might
try and assemble a simple hardware to run the examples.
I'll send you an email ASAP.

Cheers,
